name: Upload Release to itch.io

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Butler
        run: |
          curl -L https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default -o butler.zip
          unzip butler.zip
          chmod +x butler

      - name: Download Release Assets
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          out-file-path: release

      - name: Show downloaded files
        run: |
          ls -R release

      - name: Upload to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          ./butler push release YOURUSERNAME/YOURGAME:windows
