name: Upload Release to itch.io

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Butler
        run: |
          wget https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default -O butler.zip
          unzip butler.zip
          chmod +x butler

      - name: Download latest release ZIP
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir release

          gh release download \
            --repo CGdiego/Kitchen-Chaos \
            --pattern "*.zip" \
            --dir release

      - name: Show release files
        run: |
          echo "=== RELEASE ==="
          find release

      - name: Extract ZIP
        run: |
          mkdir upload

          ZIP=$(find release -name "*.zip" | head -n 1)

          if [ -z "$ZIP" ]; then
            echo "ZIP NOT FOUND"
            exit 1
          fi

          unzip -o "$ZIP" -d upload

          echo "=== UPLOAD ==="
          find upload

      - name: Upload to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          ./butler push upload charmandercg/kitchen-chaos:windows
